spring:
  kafka:
    bootstrap-servers: localhost:9094
    listener:
      ack-mode: MANUAL
      concurrency: 2   # 워커 스레드(파티션 따라 자동 분배)
    consumer:
      group-id: transcoder
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
